language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - lcov

install:
  - "[ $CXX = g++ ] && export CXX=g++ || true"
  - "[ $CXX = clang++ ] && export CXX=clang++ || true"

script:
  - chmod 755 ./make.sh ; ./make.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
