language: cpp
sudo: false
dist: bionic
compiler:
  - gcc

addons:
  apt:
    packages:
    - lcov

script:
  - chmod 755 ./make.sh ; ./make.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
