language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - g++-6
    - clang-3.8

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

script:
  - ./make.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
